### ISSUE TITLE
How this use?

### ISSUE THREAD

**Issue by unknown-gd** [JarosLucky/ents.FindInBoxRotated#1]
I try this 

local a, b = ent:GetRotatedAABB( ent:OBBMins(), ent:OBBMaxs() )
local pos = ( ent:GetPos() + ( a + b ) / 2 )

PrintTable(ents.FindInBoxRotated(ent:WorldSpaceCenter(), ent:GetAngles(), a, b, (a-b):Length()))

**Comment by JarosLucky** [comment]
A, B must be local vectors, you need to remove the function
ent:GetRotatedAABB

вс, 29 нояб. 2020 г., 08:34 PrikolMen:-b <notifications@github.com>:

**Comment by unknown-gd** [comment]
i.e. I have to use ent: OBBMins (), ent: OBBMaxs () instead of a and b, but otherwise will it work?

**Comment by JarosLucky** [comment]
I think yes

пн, 30 нояб. 2020 г., 01:35 PrikolMen:-b <notifications@github.com>:

**Comment by unknown-gd** [comment]
ok, i try

**Comment by unknown-gd** [comment]
Thanks! I did it! Example: ents.FindInBoxRotated(pos, ent:GetAngles(), mins, maxs, math.Round(mins:DistToSqr(maxs)))
